In [2]:
import pandas as pd
import numpy as np

In [3]:
sms_messages= pd.read_csv('SMSSpamCollection',sep='\t',names=['label','messages'])

In [4]:
sms_messages.describe()

label                messages
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [5]:
sms_messages.tail()

label                                           messages
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [6]:
sms_messages.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [7]:
sms_messages['label_number'] = sms_messages.label.map({"ham":0,"spam":1})

In [8]:
sms_messages.head()

label                                           messages  label_number
0   ham  Go until jurong point, crazy.. Available only ...             0
1   ham                      Ok lar... Joking wif u oni...             0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             1
3   ham  U dun say so early hor... U c already then say...             0
4   ham  Nah I don't think he goes to usf, he lives aro...             0

In [9]:
x = sms_messages.messages
y = sms_messages.label_number

In [14]:
x.shape

(5572,)

In [15]:
y.shape

(5572,)

In [16]:
from sklearn.model_selection import train_test_split


In [50]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3,random_state = 13 )

In [51]:
X_train.shape,X_test.shape

((1114,), (4458,))

In [52]:
y_train.shape,y_test.shape

((1114,), (4458,))

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
vector = CountVectorizer()

In [55]:
vector.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [56]:
X_train_dtmatrix = vector.transform(X_train)

In [57]:
X_train_dtmatrix.shape

(1114, 3501)

In [58]:
X_train_dtmatrix

<1114x3501 sparse matrix of type '<class 'numpy.int64'>'
	with 14887 stored elements in Compressed Sparse Row format>

In [59]:
X_test_dtmatrix = vector.transform(X_test)

In [60]:
X_test_dtmatrix.shape

(4458, 3501)

In [61]:
X_test_dtmatrix

<4458x3501 sparse matrix of type '<class 'numpy.int64'>'
	with 50726 stored elements in Compressed Sparse Row format>

In [62]:
from sklearn.naive_bayes import MultinomialNB

In [63]:
nb_model = MultinomialNB()

In [64]:
y_train.shape

(1114,)

In [65]:
nb_model.fit(X_train_dtmatrix,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [66]:
prediction = nb_model.predict(X_test_dtmatrix)

In [67]:
prediction.astype(np.int64)

array([0, 0, 0, ..., 0, 0, 0])

In [68]:
from sklearn import metrics

In [69]:
metrics.accuracy_score(y_test,prediction)

0.9773441004934948

In [70]:
metrics.confusion_matrix(y_test,prediction)

array([[3845,   11],
       [  90,  512]])

In [71]:
# logistic regression

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
log_model = LogisticRegression()

In [74]:
log_model.fit(X_train_dtmatrix,y_train)

/home/nazeer/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [75]:
prediction2 = log_model.predict(X_test_dtmatrix)

In [76]:
metrics.accuracy_score(y_test,prediction2)

0.9726334679228353

In [77]:
y_test < prediction
0 < 1

True

In [78]:
X_test[y_test < prediction]

4862                               Nokia phone is lovly..
216     Finally the match heading towards draw as your...
4729    I (Career Tel) have added u as a contact on IN...
4702                               I liked the new mobile
1290    Hey...Great deal...Farm tour 9am to 5pm $95/pa...
4382               Mathews or tait or edwards or anderson
1506    Total video converter free download type this ...
4490             The new deus ex game comin early next yr
2419    Madam,regret disturbance.might receive a refer...
4557                              Gettin rdy to ship comp
2173     Yavnt tried yet and never played original either
Name: messages, dtype: object

In [79]:
X_test[y_test > prediction2]

19      England v Macedonia - dont miss the goals/team...
2558    This message is brought to you by GMW Ltd. and...
1500    SMS. ac JSco: Energy is high, but u may not kn...
4616    Sunshine Quiz! Win a super Sony DVD recorder i...
1460    Bought one ringtone and now getting texts cost...
2269                    88066 FROM 88066 LOST 3POUND HELP
3548    Rock yr chik. Get 100's of filthy films &XXX p...
1718    WOW! The Boys R Back. TAKE THAT 2007 UK Tour. ...
4047        Win a £1000 cash prize or a prize worth £5000
3425    Am new 2 club & dont fink we met yet Will B gr...
1196    You have 1 new voicemail. Please call 08719181503
1318    Win the newest “Harry Potter and the Order of ...
731     Email AlertFrom: Jeri StewartSize: 2KBSubject:...
4673    Customer service announcement. We recently tri...
684     Hi I'm sue. I am 20 years old and work as a la...
415     100 dating service cal;l 09064012103 box334sk38ch
4821    Check Out Choose Your Babe Videos @ sms.shsex....
4213    Missed

In [47]:
X_test[5427]

'Santa Calling! Would your little ones like a call from Santa Xmas eve? Call 09058094583 to book your time.'

In [82]:
metrics.confusion_matrix(y_test,prediction2)

array([[3842,   14],
       [ 108,  494]])

In [83]:
len(X_test[y_test > prediction2])

108